# Generated by Django 4.0.3 on 2022-03-25 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-admitted',)},
        ),
        migrations.AddField(
            model_name='video',
            name='admitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
