# Generated by Django 4.0.3 on 2022-03-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_video_options_video_admitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='admitted',
        ),
    ]
