# Generated by Django 4.0.3 on 2022-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_videodetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='videod',
            field=models.FileField(upload_to='movie/videod.html'),
        ),
    ]
