# Generated by Django 4.0.3 on 2022-04-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_videodetail_videod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoDetail',
            new_name='VideoD',
        ),
    ]
