# Generated by Django 4.0.3 on 2022-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_videod_videod'),
    ]

    operations = [
        migrations.AddField(
            model_name='videod',
            name='thumb',
            field=models.FileField(blank=True, upload_to='thumb/%y'),
        ),
    ]
