# Generated by Django 4.0.3 on 2022-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_videod_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videod',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
