# Generated by Django 4.0.3 on 2022-04-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_tib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tib',
            old_name='moon',
            new_name='tib',
        ),
    ]
