# Generated by Django 4.0.3 on 2022-05-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_oldguard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldguard',
            old_name='bat',
            new_name='old',
        ),
    ]
