# Generated by Django 4.0.3 on 2022-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('ecanto', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
    ]
